apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgify-deployment
spec:
  selector:
    matchLabels:
      app: ledgify
  replicas: 1
  template:
    metadata:
      labels:
        app: ledgify
    spec:
      containers:
      - name: ledgify
        image: ledgify
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ledgify-service
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: ledgify